# Generated by Django 4.1 on 2023-08-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xenovaping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_pending',
            field=models.FloatField(default=0),
        ),
    ]
