branches: master

variables:
  - &file Dockerfile
  - &repo codeberg.org/${CI_REPO_OWNER}/bus.gal-web

pipeline:
  dryrun:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/amd64
      dry_run: true
      repo: *repo
      tags: latest
    when:
      event: pull_request

  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/amd64
      repo: *repo
      registry: codeberg.org
      tags: latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
    when:
      event: push