branches: master

variables:
  - &file Dockerfile
  - &repo quay.io/peprolinbot/bus.gal-web

pipeline:
  dryrun:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/amd64
      dry_run: true
      repo: *repo
      tags: latest
    when:
      event: pull_request

  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/amd64
      repo: *repo
      registry: quay.io
      tags: latest
      username:
        from_secret: quay_user
      password:
        from_secret: quay_token
    when:
      event: push